config/routes.rb
Rails.application.routes.draw do

root 'welcome#home'
get 'swag', to: 'welcome#swag'
get 'gollu/mans', to:'gollu#mans'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/gollu_controller.rb
class GolluController<ApplicationController
   def mans

   end
 end

app/controllers/concerns/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end
  def swag

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gollu/mans.html.erb
<h1> <b>its okay if u talk to dolls, the problem starts when they start answering</b></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apptest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<h1> CHutad </h1>
<%= link_to 'SWAG', swag_path %>

app/views/welcome/swag.html.erb
<h1 style = "color: red; font-size: 45px"> <em>SWAg</em> </h1>
<%= link_to 'HOME', root_path %>